### PR TITLE
Way faster...

### PR DESCRIPTION
**Pull request by ThatItalianGuy**
("[%i];"):format(str) is much faster then using str = str .. ";", like 50% faster.

NOTE: Untested with Garry's Mod methods.

### CODE REVIEW

**Comment by vercas** [comment]
Why the square brackets..?

**Comment by ThatItalianGuy** [comment]
Sorry about that, I did this well I was driving home yesterday :P they are just useless extra characters, please remove them... I also noticed I missed "oldstring".

**Comment by vercas** [comment]
I will commit soon with lots of changes, including an adaptation of this.

**Comment by Sozdatelenator** [comment]
кал

**Pull request closed without merging**
